# Version of docker-compose syntax
version: '3.8'

# Each "service" is one container
services:

  # SERVICE 2: FastAPI backend
  backend:
      build: ./backend
      ports:
        - "8000:8000"
      environment:
        DB_PASSWORD: ${DB_PASSWORD}
        DATABASE_URL: ${RDS_DATABASE_URL}
      restart: on-failure
      volumes:
        - ./backend:/app
  # SERVICE 3: React frontend
  frontend:
        build: ./frontend
        ports:
          - "3000:3000"
        depends_on:
          - backend
        env_file:
          - ./frontend/.env
        volumes:
          - ./frontend/src:/app/src

# Named volume — Docker manages this storage for you
volumes:
  postgres_data:
